navigation_motion_node:
  ros__parameters:
    success_distance_threshold: 0.1
    success_yaw_threshold: 0.1
    stuck_timeout_sec: 20.0
    stuck_distance_threshold: 0.05
    max_moving_speed: 0.5
    max_angular_speed: 1.2
    
guidance_motion_node:
  ros__parameters:
    success_distance_threshold: 0.1
    success_yaw_threshold: 0.1
    stuck_timeout_sec: 30.0
    stuck_distance_threshold: 0.05
    normal_distance_min: 0.3
    normal_distance_max: 1.0
    lost_distance_threshold: 1.2
    lost_timeout_sec: 60.0
    max_moving_speed: 0.4
    max_angular_speed: 1.2

follow_user_motion_node:
  ros__parameters:
    # Lookahead Parameters
    min_lookahead_dist: 0.3                  # Minimum lookahead distance, for safety at low speeds/standstill.
    max_lookahead_dist: 1.2                  # Maximum lookahead distance, prevents cutting corners too much.
    lookahead_time: 1.5                      # Key parameter: lookahead distance = lookahead_time * current_speed. 1.5-2.0s is a good starting point.

    # Velocity & Acceleration Parameters
    max_linear_vel: 0.75                     # Safety limit for max linear speed.
    linear_acceleration: 1.00                # Linear acceleration (m/s^2)
    linear_deceleration: 1.50                # Linear deceleration (m/s^2)
    max_angular_vel: 2.0                     # Maximum angular velocity
    max_angular_acceleration: 4.0            # Maximum angular acceleration (rad/s^2)

    # Goal Approach Parameters
    min_approach_linear_velocity: 0.00       # Minimum velocity when approaching the goal.
    approach_velocity_scaling_dist: 1.0      # Distance at which to start scaling down velocity when approaching the goal.
    goal_dist_buf: 0.15                      # Intermediate buffer distance for multi-stage goal approach.
    goal_dist_tol: 0.075                     # Goal tolerance in meters. Reduce for better accuracy.
    
    # Turning Parameters
    heading_error_for_pure_rotation: 0.75   # ~43 degrees
    min_heading_error_for_motion: 0.5       # 30 degrees

    # Following Parameters
    lagging_dist_thres: 1.5                 # Exceeding this distance is considered lagging behind.(m) 
    lost_user_timeout: 0.5                  # User not found judgment timeout. (sec)