navigation_motion_node:
  ros__parameters:
    success_distance_threshold: 0.1
    success_yaw_threshold: 0.1
    stuck_timeout_sec: 20.0
    stuck_distance_threshold: 0.05
    max_moving_speed: 1.2
    max_angular_speed: 1.2
    
guidance_motion_node:
  ros__parameters:
    success_distance_threshold: 0.1
    success_yaw_threshold: 0.1
    stuck_timeout_sec: 20.0
    stuck_distance_threshold: 0.05
    normal_distance_min: 1.2
    normal_distance_max: 2.0
    lost_distance_threshold: 3.0
    lost_timeout_sec: 20.0
    max_moving_speed: 1.5
    max_angular_speed: 1.2

follow_user_node:
  ros__parameters:
    stuck_timeout_sec: 5.0
    stuck_distance_threshold: 0.05
    follow_distance: 1.5
    max_follow_speed: 0.8