# Goal
geometry_msgs/PoseStamped target_pose
float32 speed_ratio
bool align_yaw
string nav_mode
string user_id
---
# Result
bool success
string message
---
# Feedback
string status
geometry_msgs/PoseStamped current_pose
